---
abstract: 'a bundle of WWW::Pastebin::* modules'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-WWW-Pastebin
provides:
  Task::WWW::Pastebin:
    file: lib/Task/WWW/Pastebin.pm
    version: 0.002
requires:
  WWW::Pastebin::Bot::Pastebot::Create: 0.001
  WWW::Pastebin::Many::Retrieve: 0.002
  WWW::Pastebin::NoMorePastingCom::Retrieve: 0.001
  WWW::Pastebin::NoPasteCom::Create: 0.0102
  WWW::Pastebin::PastebinCa::Create: 0.001
  WWW::Pastebin::PastebinCa::Retrieve: 0.003
  WWW::Pastebin::PastebinCom::Create: 0.003
  WWW::Pastebin::PastebinCom::Retrieve: 0.002
  WWW::Pastebin::PastieCabooSe::Retrieve: 0.001
  WWW::Pastebin::PhpfiCom::Create: 0.001
  WWW::Pastebin::PhpfiCom::Retrieve: 0.001
  WWW::Pastebin::RafbNet::Create: 0.001
  WWW::Pastebin::RafbNet::Retrieve: 0.001
  WWW::Pastebin::UbuntuNlOrg::Retrieve: 0.001
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
